### ISSUE TITLE
replace docker with podman in build and serve script

### ISSUE THREAD

**Issue by capsulecorplab** [tetrabiodistributed/papra#100]
running the static site build (and local server) via docker requires root permission on Linux, which generates build artifacts in `dist/` that are read-only and requires root permissions to remove when cleaning the build cache. Because podman doesn't require running a daemon it can run root-less, therefore can generate build artifacts that aren't read-only.

**Comment by mmroden** [comment]
Docker is the de facto standard for dependency management for releases. Not sure I want to give that up because of having to run as sudo-- will podman still avoid the "runs on my machine" situation?

-------- Original Message --------

**Comment by capsulecorplab** [comment]
docker and podman are based on the same open standard, so in theory should be able to both run the same images cross-platform with virtually identical cli commands.

**Comment by mmroden** [comment]
according to https://podman.io/, "alias docker=podman", so go for it

------- Original Message -------
