### ISSUE TITLE
Put past build instructions up somewhere

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papra#16]
Rather than delete them, put the various build iterations somewhere for people with those versions

**Comment by capsulecorplab** [comment]
Looking into this. My thought is that it would need to be a "hidden" page, as to not crowd the nav tree, but still accessible via some url https://discourse.gohugo.io/t/hidden-preview-posts/14173/11

**Comment by capsulecorplab** [comment]
Figured out how to enable hidden pages; just need to set `toc_hide: true` in the front matter https://www.docsy.dev/docs/adding-content/navigation/#section-menu
