### ISSUE TITLE
Full step file for June 25th build

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papra#78]
for the fan box

**Comment by mechatroniks-git** [comment]
@DHHwangPhD is this the correct model: Klein Filter 96mm PAPRa?

![image](https://user-images.githubusercontent.com/57600622/181063365-ed4d35a7-af03-41ae-b863-df3d4da0d6ff.png)

**Comment by mechatroniks-git** [comment]
Explosion animation: https://a360.co/3PSst8k

**Comment by mmroden** [comment]
closed by #84 and by a new assembly diagram in the main papr-print-parts project
